# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L4BVUhrXGJ6wYxjaolrbU3joIoeCb8d9
"""

import gradio as gr
import torch
import torch.nn as nn
import torchvision.models as models
from PIL import Image
import numpy as np
import albumentations as A
from albumentations.pytorch import ToTensorV2

# أ- تعريف هيكل الموديل (يجب أن يطابق ما تدربت عليه)
class RadiogenomicModel(nn.Module):
    def __init__(self, num_subtypes=5):
        super().__init__()
        self.backbone = models.resnet50(weights=None) # استخدم نفس الـ backbone
        self.backbone.fc = nn.Identity()
        self.diag_head = nn.Linear(2048, 1)
        self.genomic_head = nn.Linear(2048, num_subtypes)

    def forward(self, x):
        features = self.backbone(x)
        return self.diag_head(features), self.genomic_head(features)

# ب- تحميل الموديل والأوزان
device = torch.device("cpu") # Hugging Face المجاني يستخدم CPU
model = RadiogenomicModel(num_subtypes=5)
model.load_state_dict(torch.load("final_cmmd_model.pth", map_location=device))
model.eval()

BEST_THRESHOLD = 0.46

# ج- دالة التوقعات
def predict(input_img):
    transform = A.Compose([A.Resize(224, 224), A.Normalize(), ToTensorV2()])
    img_array = np.array(input_img)
    tensor_img = transform(image=img_array)['image'].unsqueeze(0)

    with torch.no_grad():
        d_out, g_out = model(tensor_img)
        prob = torch.sigmoid(d_out).item()
        subtype_idx = torch.argmax(g_out, dim=1).item()

    diagnosis = "MALIGNANT (خبيث)" if prob >= BEST_THRESHOLD else "BENIGN (حميد)"
    subtypes = ["Luminal A", "Luminal B", "HER2+", "Triple Negative", "Normal-like"]

    return diagnosis, f"{prob*100:.2f}%", subtypes[subtype_idx]

# د- واجهة Gradio
with gr.Blocks(theme=gr.themes.Soft()) as demo:
    gr.Markdown("# 🧬 CMMD Radiogenomics AI Analysis")
    with gr.Row():
        with gr.Column():
            img_input = gr.Image(type="pil", label="Upload Mammography")
            btn = gr.Button("Analyze", variant="primary")
        with gr.Column():
            out_diag = gr.Textbox(label="Diagnosis")
            out_conf = gr.Textbox(label="Confidence")
            out_type = gr.Textbox(label="Genomic Subtype")

    btn.click(predict, inputs=img_input, outputs=[out_diag, out_conf, out_type])

demo.launch()